#!/bin/sh
PID=$(netstat -nlp | grep :9501 | awk '{print $7}' | awk -F"/" '{ print $1 }');
COMMAND_ROOT=/work/www/robot/
case "$1" in
    start)
        if [ -n "$PID" ]
        then
                echo "process is already running or crashed"
        else
                echo "Starting Swoole server..."
		cd $COMMAND_ROOT
                $(/usr/bin/php artisan swoole start)
        fi
        ;;
    stop)
        if [ ! -n "$PID" ]
        then
              echo "$PID does not exist, process is not running"
        else
              kill  -15  $PID;
              echo "Swoole stopped"
        fi
        ;;
   restart|force-reload)
        ${0} stop
        ${0} start
        ;;
  *)
    echo "Usage: /etc/init.d/swoole {start|stop|restart|force-reload}" >&2
        exit 1
esac